//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenThanhMetro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int TicketID { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public System.DateTime ValidUntil { get; set; }
        public string BarcodeData { get; set; }
        public Nullable<int> DestinationID { get; set; }
        public Nullable<int> MachineID { get; set; }
    
        public virtual Destination Destination { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual TicketVendorMachine TicketVendorMachine { get; set; }
    }
}
